### ISSUE TITLE
When using POST method in SPiDRequest query string is not added to request URL

### ISSUE THREAD

**Issue by outlying** [schibsted/sdk-android#15]
Problem is inside of ```doInBackground``` method, when GET request is send it is created like this

    httpRequest = new HttpGet(url + getQueryAsString());

but if method is POST then query params added to request are ignored

    httpRequest = new HttpPost(url);

**Comment by oskarh** [comment]
The parameters of our post requests are added to the request body instead of to the URL as we do in our get requests. So those parameters are added using addBodyParameter instead of addQueryParameter we use for get. This class is only used internally.

It's a bit quirky how that entire class is built up, but I haven't made much changes to it as we decided a while back we didn't want to add dependencies to our library. That's going to change going forward though as Apache HTTP Client was removed in Android 6.0 this would be the same as pushing a dependency on the app in terms of extra methods and size.

I'll probably change it to Retrofit 2, that's still in beta but from what I read it'll be released before the end of the year.
