### ISSUE TITLE
Fix proper deployment routines

### ISSUE THREAD

**Issue by Nilzor** [schibsted/sdk-android#20]
Up until now the binaries have been deployed by [checking into this repo](https://github.com/schibsted/sdk-android/tree/master/SPiDSDK/repo/no/schibstedpayment/SPiD-Android). Is that a practice you want to continue with? It's not a very common practice to add all compiled binaries to a source control system

[event-sdk-android](https://github.schibsted.io/spt-dataanalytics/event-sdk-android) are using S3-buckets for the binaries. Maybe do the same here? 

The deployment should also probably happen as a part of the build routine of the master branch.

**Comment by joawan** [comment]
We have no android dev at the moment, so I cant get any resources to fix it.
I would rather have binaries automatically uploaded to github releases instead, like we do with [js-sdk releases](https://github.com/schibsted/sdk-js/releases).

Or, possible to get them on maven central?

**Comment by Nilzor** [comment]
>I would rather have binaries automatically uploaded to github releases instead

Can these be referenced as a maven dependency? If that's the case then I'm fine with that. As a consumer my only concern is that updating the binary should be as easy as changing the version number in `build.gradle` in my client app.

In any case I suggest you just keep this issue open until you have resources to look at it. I can work around this in the mean time by pulling, building and uploading the binaries to our VG repo at `http://static.vg.no/app-snarvei/javarepo`

**Comment by Nexcius** [comment]
This SDK can be referenced in Gradle using the repository `maven { url 'https://raw.github.com/schibsted/sdk-android/master/SPiDSDK/repo/' }`. You can then reference versions as normal `compile 'no.schibstedpayment:SPiD-Android:1.3.11@aar'`. 

While it is far from ideal to have artifacts in the repo like this, we are quickly moving away from this SDK and on to the new ones. Due to this, we would like to rather spend our efforts on getting feature parity on those.
